import Head from 'next/head'
import Navbar from '../components/common/Navbar'
import Footer from '../components/common/Footer'

import styles from '../styles/Home.module.css'
import Hero from '../components/ui/Hero'
import ProductCard from '../components/project/ProjectCard'

export default function Home() {
  return (
    <div className="mb-auto">
      <Head>
        <title>Dao Fund</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar/>
      <Hero/>
      <div className="w-full bg-white p-12">
            <div className="header flex items-end justify-between mb-12">
                <div className="title">
                    <p className="text-4xl font-bold text-gray-800 mb-4">
                        Newest Project
                    </p>
                    <p className="text-2xl font-light text-gray-400">
                        All article are verified by 2 experts and valdiate by the CTO
                    </p>
                </div>
            
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-12">
                <ProductCard/>
                <ProductCard/>
                <ProductCard/>
            </div>
        </div>
     
      <Footer/>

     </div>
  )
}
